## (a)

Soit $\mathcal{Y}= \{1, ..., K\}$.

On cherche à classifier les individus de $\mathcal{X}$ selon leur classe sur $\mathcal{Y}$.


Soit $g^*$ l'estimateur de risque minimal associé à cette classification.

\begin{align*}
R(g^*)    &:= \mathbb{E}\left[{1}_{\{g^*(X) \neq Y \}}\right]\\
          &= \mathbb{E}_X \mathbb{E}_{Y|X=x}\left[{1}_{\{g^*(x) \neq Y \}}\right]\\
          &= 1 - \mathbb{E}_X \mathbb{E}_{Y|X=x}\left[{1}_{\{g^*(x) = Y \}}\right]\\
          &= 1 - \mathbb{E}_X \mathbb{P} \left[g^*(x) = Y\right]\\
R(g^*)    &= 1 - \mathbb{E}_X \left[\sum_{i=1}^K \eta_i(x) {1}_{\{g^*(x) = i\}}\right]
\end{align*}


Ce risque est minimal lorsque le terme dans l'espérance est maximal.

Donc :
$$
\boxed{g^*(x) = \underset{i \in \mathcal{Y}}{\text{argmax }} \eta_i(x)}
$$

## (b)

D'après le calcul précédent, et en utilisant les définitions de $g^*$ et de $g$:

\begin{align*}
  R(g) - R(g^*)   &= 1 - \mathbb{E}_X \left[\sum_{i=1}^K \eta_i(x) {1}_{\{g(x) = i\}}\right] - 1 + \mathbb{E}_X \left[\sum_{i=1}^K \eta_i(x) {1}_{\{g^*(x) = i\}}\right]\\
                  &= \mathbb{E}_X \left[\sum_{i=1}^K \eta_i(x) {1}_{\{g^*(x) = i\}}\right] - \mathbb{E}_X \left[\sum_{i=1}^K \eta_i(x) {1}_{\{g(x) = i\}}\right]\\
                  &= \mathbb{E}_X \left[\underset{i\in \mathcal{Y}}{\max}\eta_i(x) - \mathbb{E}_X \eta_{g(x)} \right]\\
                  &= \mathbb{E}_X \left[\underset{i\in \mathcal{Y}}{\max}\eta_i(x) - \eta_{g(x)} \right]
\end{align*}

Donc :
$$
\boxed{R(g) - R(g^*) = \mathbb{E}_X \left[\underset{i\in \mathcal{Y}}{\max}\eta_i(x) - \eta_{g(x)} \right]}
$$


## (c)

On considère maintenant la règle de classification $\hat{g_n}$ approchée de $g$ et issue de
$\hat{\eta_i}$ un estimateur de $\eta_i$ obtenu à partir des données.

La règle de classification est donc la suivante :

$$
\hat{g_n}(x) = \underset{j \in \mathcal{Y}}{\text{argmax }} \hat{\eta_j}(x)
$$


$$
\begin{aligned}
\text { On a } & E_X\left[\max _{i \in y}(\eta_i(X))-\hat{\eta}_{\hat{g}_n(X)}\right] \\
& =E_X\left[\max _{i \in y} \eta_i(X)-\max _{j \in y}(\hat{\eta}(x))\right] \quad \text{par définition}
\end{aligned}
$$
Lemme: Montrons que : 
$$
\max _{x \in X} f(x)-\max_{y \in X} g(y) \leqslant \max _{z \in X}|f(z)-g(z)|
$$
$\forall x \in X, \quad f(x)-g(x) \leqslant|f(x)-g(x)|$ 


De plus, $\quad-\max _{x \in X}(g(x)) \leqslant-g(x)$


D'où,
$$
\begin {aligned}
f(x)-\max_{x\in X}(g(x)) \leqslant \left| f(x)-g(x) \right| \leqslant \underbrace{\max_{y\in X} \left| f(y)-g(y)\right |}_{\text{indépendant de x}}
\end{aligned}
$$
Donc,
$$
\begin{aligned}
\max_{z \in X} \left( f(z)-\max_{x \in X}(g(x)) \right) \leqslant \max_{y \in X}\left( \left| f(y)-g(y) \right| \right) \\
\text{D'où} \quad \max_{z\in X}(f(z))-\max_{x \in X}(g(x)) \leqslant \max_{y\in X} \left( \left| f(y)-g(y) \right| \right)
\end{aligned}
$$

Ceci achève la preuve du lemme, on peut ainsi l'appliquer dans notre cas. \newline


Finalement, $E_X\left[\max _{i \in Y}(\eta_i(X))-\max _{j\in Y}(\hat{\eta}_j(X))\right] \leqslant 2 E_X\left[\max _{i \in Y} \left| \eta_i(X)-\hat{\eta}_i(X)\right|\right]$