% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{amsmath}
\usepackage{cancel}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={STA212},
  pdfauthor={Anthony Kalaydjian - Mathieu Occhipinti},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{STA212}
\author{Anthony Kalaydjian - Mathieu Occhipinti}
\date{2023-04-29}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rm}\NormalTok{(}\AttributeTok{list=}\FunctionTok{ls}\NormalTok{())}
\FunctionTok{setwd}\NormalTok{(}\FunctionTok{getwd}\NormalTok{())}
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: le package 'ggplot2' a été compilé avec la version R 4.2.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{150}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{exercice-1-moduxe9lisation-probabiliste}{%
\section{Exercice 1 : Modélisation
probabiliste}\label{exercice-1-moduxe9lisation-probabiliste}}

\hypertarget{a}{%
\subsection{(a)}\label{a}}

Dapres le cours, on a: \[
\begin{aligned}
& R\left(g^*\right)=E_{X, Y}\left[\mathbb{1}\left\{g^*(X) \neq Y\right\}\right] \\
& =E_X\left[E_{Y \mid X}\left[\mathbb{1}\left\{g^*(X)\neq Y\right]\right]\right. \\
& =E_X\left[\frac{1}{2}-\left| \eta (X)-\frac{1}{2} \right|\right] \\
& \text { Donc } R\left(\hat{g}_n\right)-R\left(g^*\right)=E_X\left[\frac{1}{2}-\left|\hat{\eta}(X)-\frac{1}{2}\right|\right]-E_X\left[\frac{1}{2}-\left|\eta(X)-\frac{1}{2}\right|\right]. \\
& =E_X\left[\left|\eta(X)-\frac{1}{2}\right|-\left|\hat{\eta}(X)-\frac{1}{2}\right|\right] \\
& \text { Où } \left\{ \begin{array}{l}
|a|-|b|\leqslant||a|-|b||\leqslant| a-b|\leqslant 2| a-b| \\
(a, b) \in \mathbb{R}^2
\end{array}
\right.   \\
\newline 
& \text { D'où } R\left(\hat{g}_n\right)-R\left(g^*\right) \leqslant 2 E_X\left[\left| \eta(X)-\hat{\eta}(X)\right| \right] \\
&
\end{aligned}
\] \#\# (b)

Le résultat précédent nous indique que pour toute règle de
classification empirique, \(\hat{g_n}\) issue de l'estimateur
\(\hat{\eta}\) de \(\eta\), son risque associé est borné par le risque
minimal issu de la règle de Bayes \(R(g^*)\) auquel on ajoute un terme
d'erreur d'estimation de \(\eta\).

\hypertarget{exercice-2-classification-multi-classes}{%
\section{Exercice 2 : Classification
multi-classes}\label{exercice-2-classification-multi-classes}}

\hypertarget{a-1}{%
\subsection{(a)}\label{a-1}}

\hypertarget{b}{%
\subsection{(b)}\label{b}}

\hypertarget{c}{%
\subsection{(c)}\label{c}}

\hypertarget{exercice-3-impluxe9mentation-dun-perceptron-origine-des-svm}{%
\section{Exercice 3 : Implémentation d'un perceptron (origine des
SVM)}\label{exercice-3-impluxe9mentation-dun-perceptron-origine-des-svm}}

\hypertarget{a-2}{%
\subsection{(a)}\label{a-2}}

Supposons que l'on soit à l'itération \(t\) de l'algorithme, et tel que
\(m(\theta^t) \neq \emptyset\).\textbackslash{} Soit alors
\(i \in m(\theta^t)\)

D'une part:

\begin{align*}
    \langle \theta^{t+1}, \theta^* \rangle & = \langle \theta^{t} + y_i x_i, \theta^* \rangle\\
    & = \langle \theta^{t}, \theta^* \rangle + y_i \langle x_i, \theta^* \rangle\\
    & \geq \langle \theta^{t}, \theta^* \rangle + ||\theta^*||_2 \delta
\end{align*}

Par Cauchy-Schwarz:

\begin{align*}
|| \theta^{t+1} ||_2 || \theta^* ||_2 \geq \langle \theta^{t+1}, \theta^* \rangle &\geq \langle \theta^{t}, \theta^* \rangle + ||\theta^*||_2 \delta\\
&\geq \langle \theta^{t-1}, \theta^* \rangle + 2||\theta^*||_2 \delta\\
&\geq ...\\
&\geq \cancel{\langle 0, \theta^* \rangle} + t||\theta^*||_2 \delta\\
||\theta^{t+1} ||_2 || \theta^* ||_2 &\geq t||\theta^*||_2 \delta\\
\end{align*}

Donc:

\begin{equation}
    \boxed{||\theta^{t+1} ||_2 \geq t \delta}
    \label{eq:geq}
\end{equation}

D'autre part:

\begin{align*}
||\theta^{t+1}||^2  &= ||\theta^t + y_i x_i||^2\\
                    &= ||\theta^t||^2 + 2 y_i \langle \theta^t, x_i \rangle + ||y_i x_i||^2\\
                    &\leq ||\theta^t||^2 + ||x_i||^2\\
                    &\leq ||\theta^t||^2 + R^2\\
                    &\leq ||\theta^{t-1}||^2 + 2 R^2\\
                    &\leq ...\\
                    &\leq \cancel{||\theta^{0}||^2} + t R^2\\
||\theta^{t+1}||^2  &\leq t R^2
\end{align*}

Donc:

\begin{equation}
  \boxed{||\theta^{t+1}||^2  \leq t R^2}
  \label{eq:leq}
\end{equation}

Finalement, d'après \ref{geq} et \ref{leq}, on a : \[
t^2\delta^2 \leq ||\theta^{t+1}||^2  \leq t R^2
\]

Donc \(\boxed{t \leq \frac{R^2}{\delta^2}}\)

Ainsi, on a montré que si \(m(\theta^t) \neq \emptyset\), alors
\(t \leq \frac{R^2}{\delta^2}\)

Donc, au delà de \(T=\frac{R^2}{\delta^2}\) itérations, \(m(\theta^T)\)
sera vide et l'algorithme aura convergé.

\hypertarget{b-1}{%
\subsection{(b)}\label{b-1}}

Importation des données :

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\AttributeTok{file=}\StringTok{"X\_y.rda"}\NormalTok{)}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(X, y))}
\FunctionTok{names}\NormalTok{(df) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"V1"}\NormalTok{, }\StringTok{"V2"}\NormalTok{, }\StringTok{"V3"}\NormalTok{, }\StringTok{"y"}\NormalTok{)}
\NormalTok{plt1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{df) }\SpecialCharTok{+} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{V1, }\AttributeTok{y=}\NormalTok{V2, }\AttributeTok{z=}\NormalTok{y, }\AttributeTok{color=}\FunctionTok{as.factor}\NormalTok{(y)) }\SpecialCharTok{+} \FunctionTok{geom\_point}\NormalTok{()}
\NormalTok{plt1}
\end{Highlighting}
\end{Shaded}

\includegraphics{sta212_files/figure-latex/load data-1.pdf}

La variable V3 est une variable d'intercept.

\textbf{Algorithme perceptron}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{perceptron }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(X, y)\{}
\NormalTok{  theta }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{  n }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(X)}
\NormalTok{  m }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, n)}
\NormalTok{  counter }\OtherTok{\textless{}{-}} \DecValTok{0}
  
  \ControlFlowTok{while}\NormalTok{ (}\FunctionTok{length}\NormalTok{(m) }\SpecialCharTok{!=} \DecValTok{0}\NormalTok{)\{}
    \CommentTok{\#sample a random item from m}
\NormalTok{    index }\OtherTok{=} \FunctionTok{sample}\NormalTok{(m, }\DecValTok{1}\NormalTok{)}
    
    \CommentTok{\#update theta}
\NormalTok{    theta }\OtherTok{\textless{}{-}}\NormalTok{ theta }\SpecialCharTok{+}\NormalTok{ y[index]}\SpecialCharTok{*}\NormalTok{X[index,]}
    
    \CommentTok{\#calculate the new m}
\NormalTok{    temp }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(}\AttributeTok{X=}\FunctionTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, n), }\AttributeTok{FUN=}\ControlFlowTok{function}\NormalTok{(k) theta}\SpecialCharTok{\%*\%}\NormalTok{X[k,])}
\NormalTok{    criterion }\OtherTok{\textless{}{-}}\NormalTok{ y}\SpecialCharTok{*}\NormalTok{temp}
\NormalTok{    m }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(criterion}\SpecialCharTok{\textless{}}\DecValTok{0}\NormalTok{)}
\NormalTok{    counter }\OtherTok{\textless{}{-}}\NormalTok{ counter }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{  \}}
  \FunctionTok{return}\NormalTok{(}\FunctionTok{list}\NormalTok{(}\AttributeTok{theta=}\NormalTok{theta, }\AttributeTok{count=}\NormalTok{counter))}
\NormalTok{\}}

\NormalTok{res }\OtherTok{\textless{}{-}} \FunctionTok{perceptron}\NormalTok{(X, y)}
\NormalTok{theta.star }\OtherTok{\textless{}{-}}\NormalTok{ res}\SpecialCharTok{$}\NormalTok{theta}
\NormalTok{count.star }\OtherTok{\textless{}{-}}\NormalTok{ res}\SpecialCharTok{$}\NormalTok{count}

\NormalTok{theta.star}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.438710 4.537851 1.000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{count.star}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5
\end{verbatim}

L'algorithme converge en 5 itérations, et nous trouve la valeur de
\(\theta^* = (3.438710, 4.537851, 1.000000)^T\).

\hypertarget{plot}{%
\subsubsection{plot}\label{plot}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plt1 }\SpecialCharTok{+} \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept=}\SpecialCharTok{{-}}\NormalTok{theta.star[}\DecValTok{3}\NormalTok{]}\SpecialCharTok{/}\NormalTok{theta.star[}\DecValTok{2}\NormalTok{], }\AttributeTok{slope=}\SpecialCharTok{{-}}\NormalTok{theta.star[}\DecValTok{1}\NormalTok{]}\SpecialCharTok{/}\NormalTok{theta.star[}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\includegraphics{sta212_files/figure-latex/unnamed-chunk-6-1.pdf}

\end{document}
